name: adv-img
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip=22.0.2
  - ipykernel=6.4.1
  - pip:
    - scipy==1.7.3
    - numpy==1.22.1
    - matplotlib==3.5.1
    - scikit-image==0.19.1
    - opencv-python==4.5.5.62
    - tqdm==4.62.3
    - scikit-learn==1.0.2
    - PyMaxflow==1.2.13
    - imageio-ffmpeg==0.4.5